version: '3.9'

services:
  api:
    image: backend
    build: ./backend
    entrypoint:  "/bin/bash -c /data/entrypoint.sh"
    volumes:
      - ./backend/:/usr/src/app/
      - ./entrypoint.sh:/data/entrypoint.sh
    ports:
      - 8000:8000
    secrets:
      - SECRET_KEY
      - DATABASE_PASSWORD
      - EMAIL_HOST_PASSWORD
    environment:
      DEBUG: 1
#      SECRET_KEY: /run/secrets/SECRET_KEY
      DATABASE_HOST: 'db.cryptotax.nerotecs.com'
      DATABASE_NAME: 'cryptotax'
      DATABASE_USER: 'cryptotaxx'
#      DATABASE_PASSWORD: /run/secrets/DATABASE_PASSWORD
      DATABASE_PORT: 7766
      EMAIL_HOST: 'smtp.gmail.com'
      EMAIL_PORT: 587
      EMAIL_HOST_USER: 'nerotecs@gmail.com'
#      EMAIL_HOST_PASSWORD: /run/secrets/EMAIL_HOST_PASSWORD
      CONTAINER: api
    depends_on:
      - redis

  redis:
    image: redis:alpine

  celery:
    image: backend
    build: ./backend
    entrypoint:  "/bin/bash -c /data/entrypoint.sh"
    volumes:
      - ./backend/:/usr/src/app/
      - ./entrypoint.sh:/data/entrypoint.sh
    secrets:
      - SECRET_KEY
      - DATABASE_PASSWORD
      - EMAIL_HOST_PASSWORD
    environment:
      DEBUG: 1
#      SECRET_KEY: /run/secrets/SECRET_KEY
      DATABASE_HOST: 'db.cryptotax.nerotecs.com'
      DATABASE_NAME: 'cryptotax'
      DATABASE_USER: 'cryptotaxx'
#      DATABASE_PASSWORD: /run/secrets/DATABASE_PASSWORD
      DATABASE_PORT: 7766
      EMAIL_HOST: 'smtp.gmail.com'
      EMAIL_PORT: 587
      EMAIL_HOST_USER: 'nerotecs@gmail.com'
#      EMAIL_HOST_PASSWORD: /run/secrets/EMAIL_HOST_PASSWORD
      CONTAINER: celery
    depends_on:
      - redis

  celery-beat:
    image: backend
    build: ./backend
    entrypoint:  "/bin/bash -c /data/entrypoint.sh"
    volumes:
      - ./backend/:/usr/src/app/
      - ./entrypoint.sh:/data/entrypoint.sh
    secrets:
      - SECRET_KEY
      - DATABASE_PASSWORD
      - EMAIL_HOST_PASSWORD
    environment:
      DEBUG: 1
#      SECRET_KEY: /run/secrets/SECRET_KEY
      DATABASE_HOST: 'db.cryptotax.nerotecs.com'
      DATABASE_NAME: 'cryptotax'
      DATABASE_USER: 'cryptotaxx'
#      DATABASE_PASSWORD: /run/secrets/DATABASE_PASSWORD
      DATABASE_PORT: 7766
      EMAIL_HOST: 'smtp.gmail.com'
      EMAIL_PORT: 587
      EMAIL_HOST_USER: 'nerotecs@gmail.com'
#      EMAIL_HOST_PASSWORD: /run/secrets/EMAIL_HOST_PASSWORD
      CONTAINER: celery-beat
    depends_on:
      - redis

secrets:
  SECRET_KEY:
    external: true
  DATABASE_PASSWORD:
    external: true
  EMAIL_HOST_PASSWORD:
    external: true
