# Generated by Django 3.2.10 on 2021-12-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCurrency',
            fields=[
                ('tag', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='tag')),
            ],
        ),
    ]
