# Generated by Django 3.2.10 on 2021-12-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_basecurrency_coingecko_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecurrency',
            name='coingecko_name',
        ),
    ]
