# Generated by Django 3.2.10 on 2021-12-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_basecurrency_coingecko_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='coingecko_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='coingecko_name'),
        ),
    ]
