# Generated by Django 3.2.10 on 2021-12-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_currency_coingecko_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecurrency',
            name='exchange_host_name',
            field=models.CharField(default=None, max_length=150, verbose_name='exchange_host_name'),
            preserve_default=False,
        ),
    ]
