# Generated by Django 3.2.10 on 2021-12-19 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_basecurrency_exchange_host_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecurrency',
            name='exchange_host_name2',
        ),
    ]
