# Generated by Django 3.1.7 on 2021-12-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_deposit_buy_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('O', 'Order'), ('T', 'Transfer'), ('D', 'Deposit')], max_length=4),
        ),
    ]
