# Generated by Django 3.2.10 on 2021-12-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BO', 'BuyOrder'), ('SO', 'SellOrder'), ('T', 'Transfer'), ('D', 'Deposit')], max_length=4)),
                ('exchange_wallet', models.TextField(blank=True, null=True, verbose_name='exchange_wallet')),
                ('fee', models.FloatField(default=0, verbose_name='fee')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BO', 'BuyOrder'), ('T', 'Transfer'), ('D', 'Deposit')], max_length=4)),
                ('exchange_wallet', models.TextField(blank=True, null=True, verbose_name='exchange_wallet')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SO', 'SellOrder'), ('T', 'Transfer')], max_length=4)),
                ('consumer', models.PositiveIntegerField(verbose_name='consumer_id')),
                ('amount', models.FloatField(verbose_name='amount')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.currency')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.analysable')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_exchange_wallet', models.TextField(blank=True, null=True, verbose_name='from_exchange_wallet')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.currency')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.analysable')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('failed', models.BooleanField(default=False, verbose_name='failed')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.currency')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessableTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('O', 'Order'), ('T', 'Transfer'), ('D', 'Deposit')], max_length=4)),
                ('exchange_wallet', models.TextField(blank=True, null=True, verbose_name='exchange_wallet')),
                ('fee', models.FloatField(default=0, verbose_name='fee')),
                ('cooldown_until', models.DateTimeField(blank=True, null=True, verbose_name='cooldown_until')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.portfolioanalysis')),
                ('fee_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.currency')),
                ('portfolio_transaction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessableTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_exchange_wallet', models.TextField(blank=True, null=True, verbose_name='from_exchange_wallet')),
                ('amount', models.FloatField(default=0, verbose_name='amount')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.currency')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.processabletransaction')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessableOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.FloatField(default=0, verbose_name='from_amount')),
                ('to_amount', models.FloatField(default=0, verbose_name='to_amount')),
                ('from_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='processable_order_from_currency', to='portfolio.currency')),
                ('to_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='processable_order_to_currency', to='portfolio.currency')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.processabletransaction')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessableDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='amount')),
                ('taxable', models.FloatField(default=0, verbose_name='taxable')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.currency')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.processabletransaction')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='title')),
                ('error_message', models.TextField(blank=True, default=None, null=True, verbose_name='error_message')),
                ('tax_sum', models.FloatField(default=0, verbose_name='tax_sum')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.portfolioanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisTransferConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.analysistransfer')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.analysisconsumer')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisSellConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.analysissell')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.analysisconsumer')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('taxable', models.FloatField(default=0, verbose_name='taxable')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.currency')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.analysable')),
            ],
        ),
        migrations.AddField(
            model_name='analysisconsumer',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.portfolioanalysis'),
        ),
        migrations.AddField(
            model_name='analysisconsumer',
            name='consumed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.analysisconsumable'),
        ),
        migrations.AddField(
            model_name='analysisconsumable',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.portfolioanalysis'),
        ),
        migrations.CreateModel(
            name='AnalysisBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.currency')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.analysable')),
            ],
        ),
        migrations.AddField(
            model_name='analysable',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.portfolioanalysis'),
        ),
        migrations.AddField(
            model_name='analysable',
            name='fee_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.currency'),
        ),
    ]
