# Generated by Django 3.2.10 on 2021-12-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_basecurrency_coingecko_name'),
        ('tax_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioanalysis',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.basecurrency'),
        ),
    ]
