# Generated by Django 3.2.10 on 2021-12-18 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0002_alter_portfolioanalysis_base_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='processabletransaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 21, 56, 26, 257095), verbose_name='datetime'),
            preserve_default=False,
        ),
    ]
