# Generated by Django 3.2.10 on 2021-12-18 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0003_processabletransaction_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysable',
            name='fee_currency',
        ),
    ]
