# Generated by Django 3.2.10 on 2021-12-19 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0004_remove_analysable_fee_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysable',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 13, 43, 22, 965809), verbose_name='datetime'),
            preserve_default=False,
        ),
    ]
