# Generated by Django 3.2.10 on 2021-12-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0008_portfolioanalysisreport_fee_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioanalysisreport',
            name='tax_sum',
        ),
        migrations.AddField(
            model_name='analysissellconsumer',
            name='realized_profit',
            field=models.FloatField(default=0, verbose_name='realized_profit'),
        ),
        migrations.AddField(
            model_name='portfolioanalysisreport',
            name='taxable_profit_sum',
            field=models.FloatField(default=0, verbose_name='taxable_profit_sum'),
        ),
    ]
