# Generated by Django 3.1.7 on 2021-12-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0010_auto_20211224_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisconsumable',
            name='analysis',
        ),
        migrations.AddField(
            model_name='analysisconsumable',
            name='analysable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.analysable'),
            preserve_default=False,
        ),
    ]
