# Generated by Django 3.1.7 on 2021-12-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0011_auto_20211224_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisconsumer',
            name='type',
            field=models.CharField(choices=[('SO', 'SellOrder'), ('T', 'Transfer'), ('D', 'Deposit')], max_length=4),
        ),
        migrations.CreateModel(
            name='AnalysisSDepositConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxable', models.FloatField(default=0, verbose_name='taxable')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.analysisconsumer')),
            ],
        ),
    ]
