# Generated by Django 3.1.7 on 2021-12-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0012_auto_20211225_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisSDepositConsumer',
        ),
    ]
