# Generated by Django 3.1.7 on 2021-12-26 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0014_auto_20211225_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisconsumable',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisconsumer',
            name='consumed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.analysisconsumable'),
        ),
    ]
