# Generated by Django 3.1.7 on 2021-12-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0017_remove_analysisconsumable_exchange_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisconsumer',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_analysis.analysable'),
        ),
    ]
