# Generated by Django 3.1.7 on 2021-12-27 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0018_auto_20211226_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissellconsumer',
            name='consumer',
        ),
        migrations.AddField(
            model_name='analysisconsumable',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 9, 50, 38, 512479), verbose_name='datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisconsumable',
            name='price',
            field=models.FloatField(default=1, verbose_name='price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisdeposit',
            name='buy_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 9, 50, 54, 38710), verbose_name='buy_datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysissellconsumer',
            name='taxable_realized_profit',
            field=models.FloatField(default=0, verbose_name='taxable_realized_profit'),
        ),
        migrations.AlterField(
            model_name='analysisconsumer',
            name='type',
            field=models.CharField(choices=[('SO', 'SellOrder'), ('T', 'Transfer')], max_length=4),
        ),
    ]
