# Generated by Django 3.1.7 on 2021-12-27 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0019_auto_20211227_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='processabledeposit',
            name='buy_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 9, 54, 20, 388873), verbose_name='buy_datetime'),
            preserve_default=False,
        ),
    ]
