# Generated by Django 3.1.7 on 2021-12-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0020_processabledeposit_buy_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioanalysis',
            name='taxable_period',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='taxable_period'),
        ),
    ]
