# Generated by Django 3.1.7 on 2021-12-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0021_portfolioanalysis_taxable_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioanalysis',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='cooldown_until'),
        ),
        migrations.AlterField(
            model_name='portfolioanalysis',
            name='mode',
            field=models.CharField(choices=[('P', 'PROCESSING'), ('A', 'ANALYSING'), ('F', 'FINISHED')], default='P', max_length=2),
        ),
    ]
