# Generated by Django 3.1.7 on 2022-01-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0023_auto_20220101_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisconsumable',
            name='amount',
            field=models.FloatField(default=0, verbose_name='amount'),
            preserve_default=False,
        ),
    ]
