# Generated by Django 3.1.7 on 2022-01-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_analysis', '0026_currencypricecache_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioanalysisreport',
            name='realized_profit_sum',
            field=models.FloatField(default=0, verbose_name='taxable_profit_sum'),
        ),
    ]
